### ISSUE TITLE
eradius_server behaviour compilation error on Elixir 1.6.

### ISSUE THREAD

**Issue by surik** [travelping/eradius#139]
```
== Compilation error in file lib/eradiusd/coa_proxy.ex ==
** (FunctionClauseError) no function clause matching in :eradius_server.behaviour_info/1

    The following arguments were given to :eradius_server.behaviour_info/1:

        # 1
        :optional_callbacks

    (eradius) /Users/surik/Documents/prog/eradiusd/deps/eradius/src/eradius_server.erl:80: :eradius_server.behaviour_info/1
    (elixir) lib/module.ex:1016: Module.behaviour_info/2
    (elixir) lib/module.ex:1331: anonymous fn/4 in Module.check_behaviours/2
    (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/module.ex:1284: Module.check_behaviours_and_impls/4
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
```

There are two ways to fix it:
1) Add `eradius_server.behaviour_info(optional_callbacks)`
2) Rework behavior with `-callback`.

The second way is more modern.

**Comment by surik** [comment]
#140 should fix this issue
